services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: ros:iron-ros-base-jammy
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock